### ISSUE TITLE
魁力屋  川崎新城店

### ISSUE THREAD

**Issue by minoritea** [akanoren/ramens#1]
![IMG_3242](https://user-images.githubusercontent.com/3453386/100876661-07567e80-34eb-11eb-80f0-9f3a48505346.jpeg)

**Comment by dongri** [comment]
![PXL_20201219_020830304](https://user-images.githubusercontent.com/878993/102678262-9e5d4f00-41ea-11eb-9a85-ebbf0f93d1f7.jpg)

魁力屋

**Comment by dongri** [comment]
![PXL_20201219_021103655](https://user-images.githubusercontent.com/878993/102678324-eb412580-41ea-11eb-8874-c296c9a4c34f.jpg)

いただきます
