### ISSUE TITLE
とうかんや　南砂町

### ISSUE THREAD

**Issue by dongri** [akanoren/ramens#13]
![PXL_20201212_022312363](https://user-images.githubusercontent.com/878993/101970344-254f7c00-3c6d-11eb-9181-94529197fc8e.jpg)

**Comment by minoritea** [comment]
ごまが美味しそう

**Comment by dongri** [comment]
https://tabelog.com/tokyo/A1313/A131303/13009557/
`3.57`

**Comment by dongri** [comment]
このラーメン屋が先月引っ越ししたので、clonse
