### ISSUE TITLE
蒙古タンメン中本 渋谷店

### ISSUE THREAD

**Issue by minoritea** [akanoren/ramens#7]
![IMG_1793](https://user-images.githubusercontent.com/3453386/100877818-aa5bc800-34ec-11eb-9356-13c391350f67.JPEG)

**Comment by dongri** [comment]
![PXL_20201217_023548177](https://user-images.githubusercontent.com/878993/102436502-0f223100-405c-11eb-916e-1b00bcd99d37.jpg)

**Comment by dongri** [comment]
![Uploading PXL_20201217_025125795.jpg…]()

**Comment by dongri** [comment]
![PXL_20201217_025125795](https://user-images.githubusercontent.com/878993/102439664-fd438c80-4061-11eb-9d32-87f259568e5b.jpg)

**Comment by dongri** [comment]
食えたのでこのイッシュクローズ
